#! /bin/bash

# This is the main script which needs to be run.
# If there is any error while running the script, run as:
#  bash testDriver
#  we need to give the number of devices during run
# i.e. bash ./testDriver 10

source ./mainMenu
source ./buildCDD
source ./insertCDD
source ./checkcddmsg
source ./creatdevicenode
source ./buildapplication
source ./testDriverwithAppl
source ./removeDriver
source ./

while true
do
    mainMenu
    case $? in # '?' (environment variable) contains the value returned from 'mainMenu'
        '0')
            exit;
            ;;
        '1')
            buildCDD;
            ;;
        '2')
            echo "Enter NOD"
            read NOD
            insertCDD $NOD;
            ;;
        '3')
            checkcddmsg;
            ;;
        '4')
            echo "Enter Major No"
            read majorno
            creatdevicenode $majorno
            ;;
        '5')
            buildapplication;
            ;;
        '6')
            testDriverwithAppl;
            ;;
        '7')
            removeDriver;
            ;;
        '8')
            clenUp;
            ;;
        *)
            echo "Invalid Choice"
    esac
done